name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install NodeJS 14.18.1
      - name: Use Node.js 14.18.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
          cache: 'npm'

      # Check code-style server
      - name: Check server code-style
        working-directory: './server'
        run: |
          npm ci
          npm run check:codestyle
          npm run check:lint

      # Check code-style client
      - name: Check server code-style
        working-directory: './client'
        run: |
          npm ci
          npm run check:lint

      # Run server tests
      - name: Run server tests
        working-directory: './server'
        run: |
          npm run test

      # Run client tests
      - name: Run client tests
        working-directory: './client'
        run: |
          npm run test:unit